### ISSUE TITLE
Send a text message 

### ISSUE THREAD

**Issue by topthammasak** [topthammasak/topthammasak#1]

**Comment by aarmzafza** [comment]
ส่งข้อความไปหาเพื่อน 1คนได้(points 4)

**Comment by aarmzafza** [comment]
ส่งข้อความไปถึงเพื่อนภายในเวลา 1 วินาที(points 8)

**Comment by apichat1951notw** [comment]
ส่ง Sticker ได้ (points : 8)

**Comment by apichat1951notw** [comment]
ส่งแชทไปในกลุ่ม และทุกคนได้ข้อความ (points : 8)

**Comment by topthammasak** [comment]
สร้างกลุ่มแชทได้ (points : 8)
