### ISSUE TITLE
Unable to receive message

### ISSUE THREAD

**Issue by topthammasak** [topthammasak/topthammasak#3]

**Comment by topthammasak** [comment]
ส่งสติ๊กเกอร์ แล้วรูปไม่ขึ้น (points : 2 )

**Comment by apichat1951notw** [comment]
ส่งข้อความไปในกลุ่ม แล้วเพื่อนได้รับข้อมูลไม่ครบทุกคน (points : 1)

**Comment by topthammasak** [comment]
ส่งข้อความแล้วใช้เวลา 1 นาที (points : 2)
